spring:
  application:
    name: kafka-chat
  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: test-group
    listener:
      missing-topics-fatal: false

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # ? URL ???? `/` ?? ??
      register-with-eureka: true  # ? Eureka? ??? ??
      fetch-registry: true  # ? ?? ??? ?? ??
    instance:
      lease-renewal-interval-in-seconds: 15  # ? ?? ?? ?? 15?
      lease-expiration-duration-in-seconds: 20  # ? ?? ?? 20?

server:
  port: 8080  # ? Kafka Chat Service ?? ??
