server:
  port: 8082

spring:
  application:
    name: msa-starboard
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: 22
    password: 2222
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  # ??? ??? ?? ??? ID ?? ??
  celebrity:
    user:
      ids:
        - 1
        - 2
        - 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
