name: Docker, Ci/Cd, EC2

on:
  push:
    branches:
      - deploy-test

jobs:
  docker-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4
  
      - name: 현재 상황 체크
        run: |
            pwd
            ls
      - name: ec2에 SSH 접속 -> 도커 컴포즈 가동
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e  # 오류 발생 시 중지

            # 1️⃣ 기존 컨테이너 중지 및 삭제
            cd ~/app || mkdir ~/app && cd ~/app
            docker compose down

            # 2️⃣ 최신 코드 가져오기
            git pull origin main

            # 3️⃣ Docker Compose 실행
            docker compose up --build -d

            # 4️⃣ 불필요한 이미지 정리
            docker image prune -af